# Generated by Django 2.1.7 on 2019-04-19 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(max_length=255)),
                ('group_description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default='pending', max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
            ],
            options={
                'db_table': 'invitation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField()),
                ('news_author', models.TextField(max_length=255)),
                ('news_url', models.TextField(null=True)),
                ('news_source', models.TextField(null=True)),
                ('news_content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-news_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsGroup',
            fields=[
                ('news_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='rest.Group')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='rest.News')),
            ],
            options={
                'db_table': 'newsgroup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=100, unique=True)),
                ('user_key', models.TextField(max_length=100)),
                ('user_email', models.EmailField(error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist.'}, max_length=254, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(default='accept', max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.User')),
            ],
            options={
                'db_table': 'user_group',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='newsgroup',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rest.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='rest.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='rest.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='news_group',
            field=models.ManyToManyField(through='rest.NewsGroup', to='rest.News'),
        ),
    ]
