# Generated by Django 2.1.7 on 2019-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.TextField()),
                ('news_content', models.TextField()),
                ('news_author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
    ]
