# Generated by Django 2.1.7 on 2019-04-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thank',
            name='status',
            field=models.TextField(default='unread', max_length=100),
        ),
    ]
