# Generated by Django 2.1.7 on 2019-03-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercontact',
            table='user_contact',
        ),
    ]
