# Generated by Django 2.1.7 on 2019-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190222_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.URLField(null=True),
        ),
    ]
