# Generated by Django 2.1.7 on 2019-03-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190325_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruser',
            old_name='contact_id',
            new_name='useruser_id',
        ),
    ]
