# Generated by Django 2.1.7 on 2019-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20190325_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=100)),
                ('user_email', models.TextField(max_length=100)),
                ('friend_name', models.TextField(max_length=100)),
                ('friend_email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserUser',
        ),
    ]
