# Generated by Django 2.1.7 on 2019-03-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20190325_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_email',
            new_name='curuser_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_name',
            new_name='curuser_name',
        ),
    ]
