# Generated by Django 2.1.7 on 2019-04-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20190325_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(default='pending', max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Group')),
            ],
            options={
                'db_table': 'invitation',
                'managed': True,
            },
        ),
        # migrations.DeleteModel(
        #     name='Contact',
        # ),
        migrations.RemoveField(
            model_name='news',
            name='news_description',
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(through='rest.UserGroup', to='rest.Group'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='rest.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='rest.User'),
        ),
    ]
