# Generated by Django 2.1.7 on 2019-04-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20190401_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
