# Generated by Django 2.1.7 on 2019-04-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20190331_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.TextField(default='accept', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='rest.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ManyToManyField(related_name='user', through='rest.UserGroup', to='rest.Group'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rest.User'),
        ),
    ]
