# Generated by Django 2.1.7 on 2019-04-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20190408_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'ordering': ['-news_id']},
        ),
    ]
